name: David Elbe
description: Building and running a web development agency since 2003.
meta_description: "The personal website of David Elbe. Entrepreneur, developer and problem-solver."

markdown: redcarpet
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://david.elbe.me/'
author:         'David Elbe'
