name: David Elbe
description: "Building and improving web apps and digital products, every day."
meta_description: "The personal website of David Elbe. Entrepreneur, developer and problem-solver."

markdown: redcarpet
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://david.elbe.me/'
author:         'David Elbe'

gems:
  - jekyll-redirect-from
